-- MySQL Script generated by MySQL Workbench
-- Sun Sep 26 18:35:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema multiplication_table
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema multiplication_table
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `multiplication_table` DEFAULT CHARACTER SET utf8 ;
USE `multiplication_table` ;

-- -----------------------------------------------------
-- Table `multiplication_table`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multiplication_table`.`user_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multiplication_table`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multiplication_table`.`class` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multiplication_table`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multiplication_table`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `type_id` INT NOT NULL DEFAULT 0,
  `class_id` INT NULL DEFAULT NULL,
  `datetime_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `datetime_deleted` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `user_fk`
    FOREIGN KEY (`type_id`)
    REFERENCES `multiplication_table`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_fk2`
    FOREIGN KEY (`class_id`)
    REFERENCES `multiplication_table`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `multiplication_table`.`parent_relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multiplication_table`.`parent_relationship` (
  `parent_id` INT NOT NULL,
  `child_id` INT NOT NULL,
  PRIMARY KEY (`parent_id`, `child_id`),
  CONSTRAINT `parent_relationship_fk`
    FOREIGN KEY (`child_id`)
    REFERENCES `multiplication_table`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `multiplication_table`.`quiz_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multiplication_table`.`quiz_result` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `marks` INT NOT NULL,
  `datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `quiz_result_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `multiplication_table`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `multiplication_table`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multiplication_table`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number1` INT NOT NULL,
  `number2` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multiplication_table`.`quiz_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multiplication_table`.`quiz_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quiz_id` INT NOT NULL,
  `question_id` INT NOT NULL,
  `response` INT NOT NULL,
  `marks` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `quiz_details_fk`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `multiplication_table`.`quiz_result` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `quiz_details_fk2`
    FOREIGN KEY (`question_id`)
    REFERENCES `multiplication_table`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `multiplication_table`.`user_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `multiplication_table`;
INSERT INTO `multiplication_table`.`user_type` (`id`, `type_name`) VALUES (1, 'student');
INSERT INTO `multiplication_table`.`user_type` (`id`, `type_name`) VALUES (2, 'parent');
INSERT INTO `multiplication_table`.`user_type` (`id`, `type_name`) VALUES (3, 'teacher');

COMMIT;


-- -----------------------------------------------------
-- Data for table `multiplication_table`.`class`
-- -----------------------------------------------------
START TRANSACTION;
USE `multiplication_table`;
INSERT INTO `multiplication_table`.`class` (`id`, `class_name`) VALUES (DEFAULT, '2A');
INSERT INTO `multiplication_table`.`class` (`id`, `class_name`) VALUES (DEFAULT, '2B');
INSERT INTO `multiplication_table`.`class` (`id`, `class_name`) VALUES (DEFAULT, '2C');
INSERT INTO `multiplication_table`.`class` (`id`, `class_name`) VALUES (DEFAULT, '2D');
INSERT INTO `multiplication_table`.`class` (`id`, `class_name`) VALUES (DEFAULT, '2E');

COMMIT;


-- -----------------------------------------------------
-- Data for table `multiplication_table`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `multiplication_table`;
INSERT INTO `multiplication_table`.`user` (`id`, `name`, `username`, `password`, `type_id`, `class_id`, `datetime_created`, `datetime_deleted`) VALUES (DEFAULT, 'Student', 'student', 'e10adc3949ba59abbe56e057f20f883e', 1, NULL, DEFAULT, NULL);
INSERT INTO `multiplication_table`.`user` (`id`, `name`, `username`, `password`, `type_id`, `class_id`, `datetime_created`, `datetime_deleted`) VALUES (DEFAULT, 'Student\'s Parent', 'parent', 'e10adc3949ba59abbe56e057f20f883e', 2, NULL, DEFAULT, NULL);
INSERT INTO `multiplication_table`.`user` (`id`, `name`, `username`, `password`, `type_id`, `class_id`, `datetime_created`, `datetime_deleted`) VALUES (DEFAULT, 'Teacher', 'teacher', 'e10adc3949ba59abbe56e057f20f883e', 3, NULL, DEFAULT, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `multiplication_table`.`question`
-- -----------------------------------------------------
START TRANSACTION;
USE `multiplication_table`;
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 1);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 2);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 3);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 4);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 5);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 6);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 7);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 8);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 9);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 2, 10);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 1);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 2);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 3);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 4);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 5);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 6);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 7);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 8);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 9);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 3, 10);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 1);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 2);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 3);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 4);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 5);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 6);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 7);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 8);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 9);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 4, 10);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 1);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 2);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 3);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 4);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 5);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 6);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 7);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 8);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 9);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 5, 10);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 1);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 2);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 3);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 4);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 5);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 6);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 7);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 8);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 9);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 6, 10);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 1);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 2);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 3);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 4);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 5);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 6);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 7);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 8);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 9);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 7, 10);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 1);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 2);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 3);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 4);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 5);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 6);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 7);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 8);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 9);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 8, 10);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 1);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 2);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 3);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 4);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 5);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 6);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 7);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 8);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 9);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 9, 10);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 1);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 2);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 3);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 4);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 5);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 6);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 7);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 8);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 9);
INSERT INTO `multiplication_table`.`question` (`id`, `number1`, `number2`) VALUES (DEFAULT, 10, 10);

COMMIT;

